---

name: 'Detect Environment'
description: 'Install and configure aspects of helm. This action can be called with multiple steps'
inputs:
  cloud:
    description: 'Cloud (aws, azure)'
    required: false
    default: ''
  event_before:
    description: 'Event before'
    required: false
    default: '' 
  event_after:
    description: 'Event after'
    required: false
    default: '' 
  token:
    description: ''
    required: false
    default: ''

outputs:
  continue_deployment:
    description:  'Continue ceployment (yes/no)'
  deploy_env:
    description: 'Environment to deploy'
  

runs:
  using: 'node16' 
  main: 'dist/index.js'